config/routes.rb
Rails.application.routes.draw do

  #root 'tasks#index'

  resources :tasks

  devise_for :users
   devise_scope :user do
    authenticated :user do      
       root :to => 'tasks#index'
    end

    unauthenticated :user do
      root :to => 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  get 'mark_complete', :to => 'tasks#mark_complete'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  validates :title,:description, presence: true

  def self.search params
    Task.where("tasks.title LIKE :term OR tasks.description LIKE :term", :term => "%#{params}%" ) 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   protect_from_forgery with: :exception

  
  def auth_user
    redirect_to new_user_registration_url unless user_signed_in?
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :auth_user
  before_action :set_task, only: [:show, :edit, :update, :destroy,:mark_complete]
  
  # GET /tasks
  # GET /tasks.json
  def index
    @task = Task.new
    if params[:q]
      @tasks = Task.search(params[:q]).paginate(page: params[:page], per_page: 5)
    else
      @tasks = Task.where("user_id = ? or assignee_id = ?", current_user.id, current_user.id).paginate(page: params[:page], per_page: 5).order('created_at DESC')
    end
    respond_to do |format|
      format.html # index.html.erb 
      format.js   # index.js.erb  
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.build(task_params)

     respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'Task created successfully.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task updated successfully.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def mark_complete
      @task.update(is_complete: true)
      respond_to do |format|
      if @task
        format.html { redirect_to tasks_path, notice: 'Task Updated.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :user_id, :assignee_id, :is_complete)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Todo</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	<% unless user_signed_in? %>
        <li class="active"><%= link_to "Sign up", new_user_registration_path %><span class="sr-only">(current)</span></a></li>
        <li><%= link_to "Sign in ", new_user_session_path %></li>        
      </ul>
      <%else%>
      <ul class="nav navbar-nav navbar-left">
        <li class="active"><%= link_to "Home",root_path%></li>
      </ul>
      <ul class="nav navbar-nav">      	
        <li><%=link_to "Log out", destroy_user_session_path,method: :delete %></li>                  
      </ul>             
      <%end%>
    </div>
  </div>
</nav>
  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>
<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task,:html => {:class => "form-inline"}) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title,class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description ,class: "form-control",:cols => 20, :rows => 1%>
  </div>
  <div class="form-group">
    <br>
    <%= f.submit class: "btn btn-primary form-control" %>
  </div>
<% end %>

<br/>

app/views/tasks/_task.html.erb
<tr>
  <td><%= link_to task.title.titleize ,task_path(task) %></td>
  <td><%= truncate(task.description, :length => 25, :omission => '... (continued)') %></td>
  <td>
  <% if task.is_complete == true%>
   <label>
    <%= check_box_tag 'assignee_id', '1', task.is_complete, :disabled => "true"  %> Completed</label>          
  <%else%>
  <label>
      <%= check_box_tag 'assignee_id', "#{task.id}", task.is_complete, class: "rght"%> Pending</label>         
  <%end%> </td>
  <td><%= task.user.email%></td>
  <td><%= button_to "Assing", edit_task_path(task), :class => "btn btn-primary", :method => :get  %></td>
</tr>

app/views/tasks/edit.html.erb
<h1>Assign Task</h1>

<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class=>"control-label" %><br>
    <%= f.text_field :title,class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class=>"control-label" %><br>
    <%= f.text_area :description ,class: "form-control",:cols => 20, :rows => 1%>
  </div>
 <div class="form-group">
    <%= f.label :assignee_id,:class=>"control-label"  %><br>
    <%= f.select :assignee_id, options_from_collection_for_select(User.where('id != ?', current_user.id), "id", "email"), prompt: "Select Asignee" %>
  </div>
  <!-- <div class="checkbox">
    <label><%#= f.check_box :is_complete %>Complete?</label>
  </div> -->
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %> 
    <%= button_to "Details", task_path, :class => "btn btn-primary", :method => :get  %>
  </div>
<% end %>

<br/>

app/views/tasks/index.html.erb
<div class="form-inline form-group-dis">
  <div class="bs-example pull-left">
      <%#= link_to('New Task', new_task_path,:class => 'btn btn-large btn-primary')  %>
      <%= render 'form' %>
  </div>

  <div class="form-group pull-right">    
      <%= text_field_tag :q,nil,:placeholder=>"Search",:class=>"form-control"%>
      <%= submit_tag "Submit",:class=>"btn btn-primary",:id=>"search-submit"%>
  </div>
</div>
<table class="table table-hover table-bordered">
  <thead>
    <tr>      
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th>Owner</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody id="partial_content">
    <%= render(partial: 'task', collection: @tasks) %>
  </tbody>
</table>
<%= will_paginate @tasks %>

app/views/tasks/index.js.erb
$('#partial_content').html("<%=j render(partial: 'task', collection: @tasks, format: 'html') %>");

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<div class="panel-body">
	<dl>
		<dt>Title</dt>
		<dd><%= @task.title %></dd>
		<dt>Description</dt>
		<dd><%= @task.description %></dd>
		<dt>Owner</dt>
		<dd><%= @task.user.email%></dd>
	</dl>
</div>
<%= button_to "Back", tasks_path, :class => "btn btn-primary", :method => :get  %>